---

- name: "configuration play book" 
  hosts: web
  user: ubuntu
  gather_facts: true
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 60 seconds for target connection to become reachable/usable."
      command: sleep 60

  roles:
    - configure-server