- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: "yes"
  
- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install kubectl"
  become: yes
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.22.2/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: 0755

- name: "install awscli and docker"
  become: yes
  apt:
    name: ["awscli", "docker.io"]
    state: latest
    update_cache: yes

- name: "install kubectl"
  become: yes
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: 0755

- name: "install minikube dependencies"
  become: yes
  apt:
    name: ["conntrack", "socat"]
    state: latest
    update_cache: yes

- name: "start minikube"
  become: yes
  command: minikube start --vm-driver=none

- name: "check if minikube is running"
  become: yes
  shell: minikube status | grep 'Running'