- name: "Authenticate docker client"
  become: yes  
  shell: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin '{{ lookup('env', 'AWS_ECR_ACCOUNT_URL') }}'

- name: "Pull docker image from ECR"
  become: yes
  shell: docker pull '{{ lookup('env', 'AWS_ECR_ACCOUNT_URL') }}'/final-udacity-proj:latest

- name: "Create deployment"
  become: yes
  shell: kubectl create deployment final-udacity-proj --image='{{ lookup('env', 'AWS_ECR_ACCOUNT_URL') }}'/final-udacity-proj:latest

- name: "Get deployments"
  become: yes
  command: kubectl get deployments

- name: "Expose deployment to outside the cluster"
  become: yes
  command: kubectl expose deployment final-udacity-proj --type=LoadBalancer --port=80

- name: "Expose deployment to outside the cluster"
  become: yes
  shell: kubectl patch service final-udacity-proj --type='json' --patch='{{ lookup('file', 'expose_nodeport.json') }}'

- name: "Check if service is exposed in expected port"
  become: yes
  shell: kubectl get service final-udacity-proj | grep '80:31280/TCP'
