Description: >
  Stack for my final udacity project

Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources: 

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub final-udacity-security-group-${ID}
      GroupDescription: Allow port 22 (SSH) and 31280 (exposed service port)
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 31280
          ToPort: 31280
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: m4.large
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: Custom_EC2_Key_Pair
      ImageId: ami-036490d46656c4818 
      Tags:
        - Key: Name
          Value: !Sub backend-${ID}
      IamInstanceProfile: !Ref ECRReadOnlyInstanceProfile
  
  ECRReadOnlyInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: !Sub ecr-read-only-instance-profile-${ID}
      Roles: 
       - !Ref ECREC2ReadOnlyRole

  ECREC2ReadOnlyRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ecr-ec2-read-only-role-${ID}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole

  ECRReadOnlyPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ecr-read-only-policy-${ID}
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ecr:GetAuthorizationToken
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:GetRepositoryPolicy
              - ecr:DescribeRepositories
              - ecr:ListImages
              - ecr:DescribeImages
              - ecr:BatchGetImage
              - ecr:GetLifecyclePolicy
              - ecr:GetLifecyclePolicyPreview
              - ecr:ListTagsForResource
              - ecr:DescribeImageScanFindings
            Resource:
              - "*"
      Roles:
        - !Ref ECREC2ReadOnlyRole