version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.2.0

jobs:
  analyze:
    docker:
      - image: python:3.7.3-stretch
    
    working_directory: ~/repo
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            make setup
            make install_dependencies
            make install_hadolint

      - save_cache:
          paths:
            - ./final
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run lint
          command: |
            . final/bin/activate
            make lint
  
workflows:
  default:
    jobs:
      - analyze
      - aws-ecr/build-and-push-image:
          requires: [analyze]
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: false
          dockerfile: Dockerfile
          path: .
          region: AWS_REGION
          repo: final-udacity-proj
          tag: "$CIRCLE_BUILD_NUM"     
      